openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /clients:
    get:
      summary: List all clients
      operationId: listClients
      tags:
        - clients
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          type: integer
          format: int32
      responses:
        "200":
          description: A paged array of clients
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
          schema:
            $ref: '#/definitions/Clients'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create a client
      operationId: createClients
      tags:
        - clients
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /clients/{clientId}:
    get:
      summary: Info for a specific client
      operationId: showClientById
      tags:
        - clients
      parameters:
        - name: clientId
          in: path
          required: true
          description: The id of the client to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/Clients'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /products:
    get:
      summary: List all products
      operationId: listProducts
      tags:
        - products
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          type: integer
          format: int32
      responses:
        "200":
          description: A paged array of products
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
          schema:
            $ref: '#/definitions/Products'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create a product
      operationId: createProducts
      tags:
        - products
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /products/{productId}:
    get:
      summary: Info for a specific product
      operationId: showProductById
      tags:
        - products
      parameters:
        - name: productId
          in: path
          required: true
          description: The id of the product to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/Products'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /purchases:
    get:
      summary: List all purchases
      operationId: listPurchases
      tags:
        - purchases
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          type: integer
          format: int32
      responses:
        "200":
          description: A paged array of purchases
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
          schema:
            $ref: '#/definitions/Purchases'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create a purchase
      operationId: createPurchases
      tags:
        - purchases
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /purchases/{purchaseId}:
    get:
      summary: Info for a specific purchase
      operationId: showPurchaseById
      tags:
        - purchases
      parameters:
        - name: purchaseId
          in: path
          required: true
          description: The id of the purchase to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/Purchases'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /paymentTypes:
    get:
      summary: List all paymentTypes
      operationId: listPaymentTypes
      tags:
        - paymentTypes
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          type: integer
          format: int32
      responses:
        "200":
          description: A paged array of paymentTypes
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
          schema:
            $ref: '#/definitions/PaymentTypes'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create a paymentType
      operationId: createPaymentTypes
      tags:
        - paymentTypes
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /paymentTypes/{paymentTypeId}:
    get:
      summary: Info for a specific paymentType
      operationId: showPaymentTypeById
      tags:
        - paymentTypes
      parameters:
        - name: paymentTypeId
          in: path
          required: true
          description: The id of the paymentType to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/PaymentTypes'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /purchaseItems:
    get:
      summary: List all purchaseItems
      operationId: listPurchaseItems
      tags:
        - purchaseItems
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          type: integer
          format: int32
      responses:
        "200":
          description: A paged array of purchaseItems
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
          schema:
            $ref: '#/definitions/PurchaseItems'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create a purchaseItem
      operationId: createPurchaseItems
      tags:
        - purchaseItems
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /purchaseItems/{purchaseItemId}:
    get:
      summary: Info for a specific purchaseItem
      operationId: showPurchaseItemById
      tags:
        - purchaseItems
      parameters:
        - name: purchaseItemId
          in: path
          required: true
          description: The id of the purchaseItem to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/PurchaseItems'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /payments:
    get:
      summary: List all payments
      operationId: listPayments
      tags:
        - payments
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          type: integer
          format: int32
      responses:
        "200":
          description: A paged array of payments
          headers:
            x-next:
              type: string
              description: A link to the next page of responses
          schema:
            $ref: '#/definitions/Payments'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Create a payment
      operationId: createPayments
      tags:
        - payments
      responses:
        "201":
          description: Null response
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /payments/{paymentId}:
    get:
      summary: Info for a specific payment
      operationId: showPaymentById
      tags:
        - payments
      parameters:
        - name: paymentId
          in: path
          required: true
          description: The id of the payment to retrieve
          type: string
      responses:
        "200":
          description: Expected response to a valid request
          schema:
            $ref: '#/definitions/Payments'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  


definitions:
  Client:
    type: "object"
    required:
      - id
      - description
    properties:
      id:
        type: int
      description:
        type: string
  Clients:
    type: array
    items:
      $ref: '#/definitions/Client'
  Product:
    type: "object"
    required:
      - id
      - code
      - reference
    properties:
      id:
        type: int
      code:
        type: string
      reference:
        type: string
  Products:
    type: array
    items:
      $ref: '#/definitions/Product'
  Purchase:
    type: "object"
    required:
      - id
      - reference
      - purchaseDate
      - total
      - image
    properties:
      id:
        type: int
      reference:
        type: string
      purchaseDate:
        type: date
      total:
        type: number
      image:
        type: string
  Purchases:
    type: array
    items:
      $ref: '#/definitions/Purchase'
  PaymentType:
    type: "object"
    required:
      - id
      - reference
      - code
    properties:
      id:
        type: int
      reference:
        type: string
      code:
        type: string
  PaymentTypes:
    type: array
    items:
      $ref: '#/definitions/PaymentType'
  PurchaseItem:
    type: "object"
    required:
      - id
      - price
      - quantity
    properties:
      id:
        type: int
      price:
        type: number
      quantity:
        type: number
  PurchaseItems:
    type: array
    items:
      $ref: '#/definitions/PurchaseItem'
  Payment:
    type: "object"
    required:
      - id
      - reference
      - amount
    properties:
      id:
        type: int
      reference:
        type: string
      amount:
        type: number
  Payments:
    type: array
    items:
      $ref: '#/definitions/Payment'

  Error:
    type: "object"
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
